start: 2021073118
end: 2021083118
step: PT6H
window_length: PT6H
# Change source_dir to your database path
source_dir: /work/noaa/da/maryamao/COMPO/gfs_aerosol
type: fc
model: gfs_aero_metadata
experiment: oper
resolution: c96
file_types:
    - coupler.res
    - fv_core.res.nc
