start: 2021-08-01T00:00:00Z
end: 2021-08-31T18:00:00Z
provider: nasa
type: obs
window_length: PT6H
# Replace source_path with the full path to the data files on the selected platform.
source_path: /work/noaa/da/eric/r2d2_input_data
obs_type: smap_ssm