start: 2021080100
end: 2021083118
offset: PT3H
window_length: PT6H
# Change source_dir to your database path
source_dir: /work2/noaa/da/dheinzel/ensemble
type: fc_ens
model: gfs_metadata
experiment: oper
resolution: c384
first_member: 1
last_member: 80
file_types:
    - coupler.res
