# Change download_dir to a local path
download_dir: /work/noaa/da/eric/r2d2_input_data
start: 2021073118
end: 2021080118
step: PT6H
gfs_file_types:
    - coupler.res
    - fv_core.res.nc
    - fv_core.res.tile1.nc
    - fv_core.res.tile2.nc
    - fv_core.res.tile3.nc
    - fv_core.res.tile4.nc
    - fv_core.res.tile5.nc
    - fv_core.res.tile6.nc
    - fv_srf_wnd.res.tile1.nc
    - fv_srf_wnd.res.tile2.nc
    - fv_srf_wnd.res.tile3.nc
    - fv_srf_wnd.res.tile4.nc
    - fv_srf_wnd.res.tile5.nc
    - fv_srf_wnd.res.tile6.nc
    - fv_tracer.res.tile1.nc
    - fv_tracer.res.tile2.nc
    - fv_tracer.res.tile3.nc
    - fv_tracer.res.tile4.nc
    - fv_tracer.res.tile5.nc
    - fv_tracer.res.tile6.nc
    - phy_data.tile1.nc
    - phy_data.tile2.nc
    - phy_data.tile3.nc
    - phy_data.tile4.nc
    - phy_data.tile5.nc
    - phy_data.tile6.nc
