start: 2020121421
end: 2021011221
step: PT6H
provider: ncdiag
type: obs
window_length: PT6H
# Replace target_path with the full path to the R2D2_SHARED database on the selected HPC platform.
target_path: /Users/eric2/R2D2
obs_types:
    - aircraft
    - amsua_metop-a
    - amsua_metop-b
    - amsua_metop-c
    - amsua_n15
    - amsua_n18
    - amsua_n19
    - atms_n20
    - atms_npp
    - avhrr3_metop-a
    - avhrr3_n18
    - cris-fsr_n20
    - cris-fsr_npp
    - gome_metop-a
    - gome_metop-b
    - hirs4_metop-a
    - hirs4_n19
    - iasi_metop-a
    - iasi_metop-b
    - mhs_metop-a
    - mhs_metop-b
    - mhs_metop-c
    - mhs_n19
    - omi_aura
    - ompsnp_npp
    - ompstc8_npp
    - rass_tv
    - satwind
    - sbuv2_n19
    - scatwind
    - seviri_m08
    - seviri_m11
    - sfc
    - sfcship
    - sondes
    - ssmis_f17
    - ssmis_f18
    - sst
    - vadwind