start: 2010010100
end: 2010010100
step: P1D
window_length: PT6H
# Change source_dir to your database path
source_path: /work/noaa/da/eric/r2d2_input_data
type: fc_ens
members:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
model: l95
experiment: oper
resolution: 40